server:
  port: 8081
spring:
  profiles:
    default: local
  h2:
    console:
      enabled: true  # H2 웹 콘솔을 사용하겠다는 의미
      path: /test  # 콘솔의 경로
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1111
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      format_sql: true
logging:
  path: /Users/jooheeyeon/data/app_logs
  max-size: 500MB
  max-history: 10
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  file:
    name: taco-cloud.log
    path: /Users/jooheeyeon/data/app_logs
  level:
    org.springframework.web: DEBUG
    org.springframwork.security: DEBUG
    org.hibernate: debug
management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      cors:
        allowed-methods: GET,POST
      exposure:
        include: '*'
  health:
    diskspace:
      enabled: true
taco:
  orders:
    page-size: 20
server:
  port: 8082